lang: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx
  - jruby
script: bundle exec rspec
notifications:
  email:
    recipients:
      - toqoz403@gmail.com
    on_success: change
    on_failure: always
